INSERT INTO product(name,price,count,image) VALUES ('Beanie',18.00,23,'/img/beanie.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Belt',55.00,10,'/img/belt.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Cap',16.00,0,'/img/cap.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Sunglasses',90.00,445,'/img/sunglasses.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Hoodie',42.00,2,'/img/hoodie.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Hoodie with Logo',1,45.00,'/img/hoodie-with-logo.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Hoodie with Pocket',0,35.00,'/img/hoodie-with-pocket.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Hoodie with Zipper',10,45.00,'/img/hoodie-with-zipper.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Long Sleeve Tee',23,25.00,'/img/long-sleeve-tee.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Polo',20.00,890,'/img/polo.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Tshirt',18.00,45,'/img/tshirt.jpg');
INSERT INTO product(name,price,count,image) VALUES ('Vneck Tshirt',18.00,3,'/img/vneck-tee.jpg');