INSERT INTO product(name,price,image) VALUES ('Beanie',18.00,'/img/beanie.jpg');
INSERT INTO product(name,price,image) VALUES ('Belt',55.00,'/img/belt.jpg');
INSERT INTO product(name,price,image) VALUES ('Cap',16.00,'/img/cap.jpg');
INSERT INTO product(name,price,image) VALUES ('Sunglasses',90.00,'/img/sunglasses.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie',42.00,'/img/hoodie.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Logo',45.00,'/img/hoodie-with-logo.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Pocket',35.00,'/img/hoodie-with-pocket.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Zipper',45.00,'/img/hoodie-with-zipper.jpg');
INSERT INTO product(name,price,image) VALUES ('Long Sleeve Tee',25.00,'/img/long-sleeve-tee.jpg');
INSERT INTO product(name,price,image) VALUES ('Polo',20.00,'/img/polo.jpg');
INSERT INTO product(name,price,image) VALUES ('Tshirt',18.00, '/img/tshirt.jpg');
INSERT INTO product(name,price,image) VALUES ('Vneck Tshirt',18.00,'/img/vneck-tee.jpg');