INSERT INTO product(name,price,image) VALUES ('Beanie',18.00,'/public/img/beanie.jpg');
INSERT INTO product(name,price,image) VALUES ('Belt',55.00,'/public/img/belt.jpg');
INSERT INTO product(name,price,image) VALUES ('Cup',16.00,'/public/img/cup.jpg');
INSERT INTO product(name,price,image) VALUES ('Sunglasses',90.00,'/public/img/sunglasses.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie',42.00,'/public/img/hoodie.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Logo',45.00,'/public/img/hoodie-with-logo.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Pocket',35.00,'/public/img/hoodie-with-pocket.jpg');
INSERT INTO product(name,price,image) VALUES ('Hoodie with Zipper',45.00,'/public/img/hoodie-with-zipper.jpg');
INSERT INTO product(name,price,image) VALUES ('Long Sleeve Tee',25.00,'/public/img/long-sleeve-tee.jpg');
INSERT INTO product(name,price,image) VALUES ('Polo',20.00,'/public/img/polo.jpg');
INSERT INTO product(name,price,image) VALUES ('Tshirt',18.00,'/public/img/tshirt.jpg');
INSERT INTO product(name,price,image) VALUES ('Vneck Tshirt',18.00,'/public/img/vneck-tee.jpg');